/*
 * Copyright (c) 2018 Anzen Soluciones S.A. de C.V.
 * Mexico D.F.
 * All rights reserved.
 *
 * THIS SOFTWARE IS  CONFIDENTIAL INFORMATION PROPIETARY OF ANZEN SOLUCIONES.
 * THIS INFORMATION SHOULD NOT BE DISCLOSED AND MAY ONLY BE USED IN ACCORDANCE THE TERMS DETERMINED BY THE COMPANY ITSELF.
 */
GRANT ALL PRIVILEGES ON DATABASE abanking_error_matrix TO abanking_matrix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO abanking_matrix;
